sudo: required
language: node_js
services:
  - docker
node_js:
  - 'node'
notifications:
    email:
      - olaakkonen@gmail.com
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
install: true
script:
  - sudo bash scripts/build.sh
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: chmod +x scripts/postbuild.sh && scripts/postbuild.sh
